### ISSUE TITLE
Cannot find module 'hapi' in order and customer packages

### ISSUE THREAD

**Issue by RezaOwliaei** [geekhouseteam/yumbox#1]
After `npm install`, I tried to run `npm test` on Order and Customer packages.
This is my terminal message:

> > yumbox.order@0.0.0 test /home/reza/Projects/yumbox/order
> > NODE_ENV=test mocha
> 
> 
> Error: Cannot find module 'hapi'

What I guess is you have missed `npm install hapi --save`

**Comment by seekasra** [comment]
solved on 4089c7128b6cf85f79635054931911a853f9dff1
